language: python
python:
  - "2.7"

before_install: scripts/before_install.sh
install: scripts/install.sh
script: npm test

deploy:
  provider: heroku
  api_key:
    secure: hHFVh5+TA5U1iyFgqQuzLSjRrN4BFWEyUerUUtn589NiMDJFtE3SA1okJIQTlq2w/iAhBqjgMoDG0rMB6NVM/i7oobMdlQJfSOEt3FlCFGl+0r2RaHxF4YaCDMEjCv/+y6Of0ifjAHwYF/p0mu9WwM86Yhc4ajfiYI602i3i4Xs=
  app:
    master: bce-simulation
