language: python
python:
  - "2.7"

env:
  global:
    - secure: "Ij2Bnf2yxM3R2qbuxjDj+TyFft92dc11yfYIn3FzSLaB25URzukypNNrDiPUercC+VWsuM6CiVh5uPhCmBWGhWlY7rJzc7O75/j34tTcJqXx4oDV7SV1GYK4PtWN0F6L9pUp5jJvH0XcDn8KAKCMtQigP1D6MLweGd4AkkbaD/o="

before_install: sudo apt-get update -qq
install: scripts/install.sh
script: npm test || exit 1
#after_success: scripts/deploy.sh

deploy:
  provider: heroku
  api_key: hHFVh5+TA5U1iyFgqQuzLSjRrN4BFWEyUerUUtn589NiMDJFtE3SA1okJIQTlq2w/iAhBqjgMoDG0rMB6NVM/i7oobMdlQJfSOEt3FlCFGl+0r2RaHxF4YaCDMEjCv/+y6Of0ifjAHwYF/p0mu9WwM86Yhc4ajfiYI602i3i4Xs=
  app: bce-simulation
