language: python
python:
  - "2.7"

# for container-based infrastructure:
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

install: scripts/install.sh
script: python test.py && npm test

deploy:
  provider: heroku
  strategy: api
  buildpack: https://github.com/ddollar/heroku-buildpack-multi.git#d5b4b977e515c51f23c6853107b03b6cd5ee53c2
  api_key:
    secure: B1wwpP0Qq5FyaIgBi8ckBaES6OGDTaYWUHQc0DXvsXr0m66DsS2rigsmIxxuASySzD13x4jtzQ+7QmIxUsRy4S/IuLIjD+YRSAm2cZPf3Xf8KBim/k2HEupsW8+vciUhjYKkvBwgw4xGExNN0x9fH9yziTPlyI4GwkHgVkmZhlw=
  app:
    master: bce-simulation-dev
    production: bce-simulation
